library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;
use IEEE.std_logic_unsigned.ALL;


entity lab_audio_top is
	Port(
			clk : in STD_LOGIC;
			btnC : in STD_LOGIC;
			btnCpuReset : in STD_LOGIC;
			sw : in  STD_LOGIC_VECTOR (15 downto 0);
			led : out  STD_LOGIC_VECTOR (15 downto 0);
			seg : out STD_LOGIC_VECTOR(6 downto 0);
			an : out STD_LOGIC_VECTOR(7 downto 0);
			ampPWM : out STD_LOGIC;
			ampSD : out STD_LOGIC			 
	);

end lab_audio_top;

architecture something of lab_audio_top is
	-- Main clock: either push button after deboucing for hardware implementation or straight clk for simulation
	signal btncdebaunched : STD_LOGIC;
	signal reset : STD_LOGIC;
    	
	signal clk200k : STD_LOGIC;	
	signal segout : std_logic_vector(31 downto 0);
	
	
begin
	
    -- Instantiate the core
    -- The core is provided with: 
    -- clk: 200KHz clock
    -- reset: asynchronous reset which is active high
    -- sw: switch states
    -- ampPWM and ampSD: outputs generated by lab_core
    core: entity work.lab_core port map(clk=>clk200k,reset=>reset,segout=>segout,sw=>sw,ampPWM=>ampPWM,ampSD=>ampSD);
    
    -- Clock divider: 
    -- Divide the 100MHz clock to obtain 200KHz to drive the audio logic.
    ckdiv200: entity work.ckdiv port map(clk=>clk,reset=>reset,top=>std_logic_vector(to_unsigned(249,32)),sout=>clk200k);


 
    
  
	-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    -- DO NOT MODIFY HEREAFTER -- DO NOT MODIFY HEREAFTER -- DO NOT MODIFY HEREAFTER -- DO NOT MODIFY HEREAFTER -- DO NOT MODIFY HEREAFTER -- DO NOT MODIFY HEREAFTER -- DO NOT MODIFY HEREAFTER -- 
    -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    
	-- Instantiate a debounce circuit: the central button is debounced. The result is the signal manualclk
	compdebouncer : entity work.debounce port map(clk=>clk,button=>btnC,result=>btncdebaunched);
	
	-- Set the LEDs to some state
	led(15 downto 1) <= (others=>'0');
    led(0)<=clk200k;
	
    -- The reset is directly connected to btnCpuReset. btnCpuReset is active low. reset is active high
	reset <= not btnCpuReset;

	-- The following component uses all 8 7-segment displays to show: r
	display: entity work.hexto7seg port map(clk=>clk,
													d7=>segout(31 downto 28),d6=>segout(27 downto 24), 
													d5=>segout(23 downto 20), d4=>segout(19 downto 16),
													d3=>segout(15 downto 12), d2=>segout(11 downto 8),
													d1=>segout(7 downto 4), d0=>segout(3 downto 0),
													blink=>"00000000",
													q=>seg,
													active=>an
												);
end something;

